CREATE TABLE IF NOT EXISTS antispam (
   rowid INTEGER PRIMARY KEY AUTOINCREMENT,
   uid TEXT NOT NULL,
   command TEXT NOT NULL,
   time TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS botactions (
   action TEXT PRIMARY KEY,
   count INTEGER NOT NULL
) WITHOUT ROWID;

CREATE TABLE IF NOT EXISTS admins (
   uid TEXT PRIMARY KEY
) WITHOUT ROWID;
